# Generated by Django 2.1.7 on 2019-02-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoHistorial', '0003_auto_20190223_2128'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reporte',
            managers=[
            ],
        ),
    ]
