# Generated by Django 2.1.7 on 2019-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoHistorial', '0006_auto_20190304_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivosTelevisores/%D/%m/%y'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/%D/%m/%y'),
        ),
    ]
