# Generated by Django 2.1.7 on 2019-03-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoHistorial', '0007_auto_20190304_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/%Y/%m/%D'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/%Y/%m/%D'),
        ),
    ]
