# Generated by Django 2.1.7 on 2019-03-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoHistorial', '0009_auto_20190304_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
