# Generated by Django 2.1.7 on 2019-03-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoHistorial', '0012_auto_20190305_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='chasis',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='control_remoto',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='display',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='firmware',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='fuente',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='main',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='modelo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='modelo_equivalente',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='modo_servicio',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
